name: Central production deployment

on:
  workflow_dispatch:
    inputs:
      force:
        description: Force redeploy
        required: false
        default: false
        type: boolean
  push:
    branches: [main]
    paths:
      - '.ops-trigger/hub.txt'

permissions:
  contents: read

jobs:
  deploy-hub:
    concurrency:
      group: deploy-hub
      cancel-in-progress: true
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service: hub
      force: ${{ github.event_name == 'push' || inputs.force }}
    secrets: inherit
